const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./app.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Email",
      description: "Trigger OTP and verify Email Address",
    },
    {
      name: "User",
      description: "Sign Up , Login and Logout users",
    },
  ],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "authorization",
      in: "header",
    },
  },
  definitions: {
    User: {
      name: "Jhon Doe",
      age: 29,
      parents: {
        father: "Simon Doe",
        mother: "Marie Doe",
      },
      diplomas: [
        {
          school: "XYZ University",
          year: 2020,
          completed: true,
          internship: {
            hours: 290,
            location: "XYZ Company",
          },
        },
      ],
    },
    AddUser: {
      $name: "Jhon Doe",
      $age: 29,
      about: "",
    },
    VerificationKey: { verification_key: "encoded" },
  },
};

// const controlSwagger = async () => {
swaggerAutogen(outputFile, endpointsFiles, doc);
// };
// module.exports = controlSwagger;
